export { HomePage } from './Home';
export { TournamentsPage } from './Tournaments';
export { TeamsPage } from './Teams';
export { GamesPage } from './Games';
export { CalendarPage } from './Calendar';
export { ProfilePage } from './Profile';
export { SettingsPage } from './Settings';
export { AdminPage } from './Admin';
export { TeamCreatePage } from './TeamCreate';
export { TeamDetailPage } from './TeamDetail';
export { GameDetailPage } from './GameDetail';
export { TournamentDetailPage } from './TournamentDetail';
export { LeaderboardsPage } from './Leaderboards';
export { NotificationsPage } from './Notifications';
export { DiscordAdminPage } from './DiscordSettings';
export { BookingPage } from './Booking';
export { TeacherTimePage } from './TeacherTimePage';
export { TournamentEmbedPage } from './embed/TournamentEmbedPage';
export { TeamEmbedPage } from './embed/TeamEmbedPage';
export { TVDisplayPage } from './TVDisplayPage';
export { TVRecruitmentPage } from './TVRecruitmentPage';
export { ScrimsPage } from './ScrimsPage';
export { NewsPage } from './NewsPage';
export { NewsDetailPage } from './NewsDetailPage';
export { DiscordCallbackPage } from './DiscordCallbackPage';
export { default as BugReportPage } from "./BugReportPage";
export { default as IncidentPage } from "./IncidentPage";
